<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ledger" nsURI="urn:org.nasdanika.ledger" nsPrefix="org.nasdanika.ledger">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Тест русской документации в модели."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Ledger"/>
  <eClassifiers xsi:type="ecore:EClass" name="УчётныйЦентр" eSuperTypes="#//ЭлементМодели"/>
  <eClassifiers xsi:type="ecore:EClass" name="ЭлементМодели" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="наименование" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="описание" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organization"/>
  <eClassifiers xsi:type="ecore:EClass" name="LegderContainer" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Счёт"/>
  <eClassifiers xsi:type="ecore:EClass" name="Asset"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Субъект"/>
</ecore:EPackage>
